# Content:
1. [Row-reduction/Elimination](#1.-Row-reduction/Elimination)
2. [Elimination followed by substitution](#2.-Elimination-followed-by-substitution)
    > [2.1. Elimination: Transform of A to U](#2.1.-Elimination:-Transform-of-A-to-U)    
    > [2.2. Backward substitution (bottom to top)](#2.2.-Backward-substitution-(bottom-to-top))  
    > [2.3. Generalizing elimination followed by substitution](#2.3.-Generalizing-elimination-followed-by-substitution )

## 1. Row-reduction/Elimination

![board%20work%20-5.jpg](boardwork/board%20work%20-5.jpg)

In [1]:
import numpy as np

A=np.array([[2,0,-1],[6,5,3],[2,-1,0]])
b=np.array([2,7,4])

#=== Augmented matrix
A1=np.zeros([3,4])
A1[0:3,0:3]=A.copy()
A1[0:3,3]=b.copy()

print('The augmented matrix [A|b] is:\n',A1)

The augmented matrix [A|b] is:
 [[ 2.  0. -1.  2.]
 [ 6.  5.  3.  7.]
 [ 2. -1.  0.  4.]]


Use the first row of A1 to eliminate the 'rest' of the first column of A1

In [2]:
A1[1,:]=A1[1,:]-(A1[1,0]/A1[0,0])*A1[0,:]
A1[2,:]=A1[2,:]-(A1[2,0]/A1[0,0])*A1[0,:]
print('After subtracting row-1 from row-2 and row-3:\n',A1)

After subtracting row-1 from row-2 and row-3:
 [[ 2.  0. -1.  2.]
 [ 0.  5.  6.  1.]
 [ 0. -1.  1.  2.]]


Use the second row of A1 to eliminate the 'rest' of the second column of A1

In [3]:
A1[0,:]=A1[0,:]-(A1[0,1]/A1[1,1])*A1[1,:]
A1[2,:]=A1[2,:]-(A1[2,1]/A1[1,1])*A1[1,:]
print('After subtracting row-2 from row-1 and row-3:\n',A1)

After subtracting row-2 from row-1 and row-3:
 [[ 2.   0.  -1.   2. ]
 [ 0.   5.   6.   1. ]
 [ 0.   0.   2.2  2.2]]


Use the third row of A1 to eliminate the 'rest' of the third column of A1

In [4]:
A1[0,:]=A1[0,:]-(A1[0,2]/A1[2,2])*A1[2,:]
A1[1,:]=A1[1,:]-(A1[1,2]/A1[2,2])*A1[2,:]
print('After subtracting row-3 from row-1 and row-2:\n',A1)

After subtracting row-3 from row-1 and row-2:
 [[ 2.   0.   0.   3. ]
 [ 0.   5.   0.  -5. ]
 [ 0.   0.   2.2  2.2]]


Now scale all the rows

In [5]:
A1[0,:]=A1[0,:]/A1[0,0]
A1[1,:]=A1[1,:]/A1[1,1]
A1[2,:]=A1[2,:]/A1[2,2]
print('...and finally, we have:\n',A1)

...and finally, we have:
 [[ 1.   0.   0.   1.5]
 [ 0.   1.   0.  -1. ]
 [ 0.   0.   1.   1. ]]


In [6]:
import numpy as np

A=np.array([[2,0,-1],[6,5,3],[2,-1,0]])
b=np.array([2,7,4])

#=== Augmented matrix
A1=np.zeros([3,4])
A1[0:3,0:3]=A.copy()
A1[0:3,3]=b.copy()

print('The augmented matrix [A|b] is:\n',A1)

for i in range(0,3):
    for j in range(0,3):
        if i != j:
            A1[j,:]=A1[j,:]-(A1[j,i]/A1[i,i])*A1[i,:]

print('The augmented matrix [A|b] after row-reduction is:\n',A1)

for i in range(0,3):
    A1[i,:]=A1[i,:]/A1[i,i]

x=np.zeros(3)
x=A1[:,3]
print('The solutions is:\n',x)

The augmented matrix [A|b] is:
 [[ 2.  0. -1.  2.]
 [ 6.  5.  3.  7.]
 [ 2. -1.  0.  4.]]
The augmented matrix [A|b] after row-reduction is:
 [[ 2.   0.   0.   3. ]
 [ 0.   5.   0.  -5. ]
 [ 0.   0.   2.2  2.2]]
The solutions is:
 [ 1.5 -1.   1. ]


## 2. Elimination followed by substitution 

![board%20work%20-7.jpg](boardwork/board%20work%20-7.jpg)

In [7]:
import numpy as np

A=np.array([[2,1,1],[1,2,1],[1,1,2]])
b=np.array([1,2,3])

#=== Augmented matrix
A1=np.zeros([3,4])
A1[0:3,0:3]=A.copy()
A1[0:3,3]=b.copy()

print('The augmented matrix [A|b] is:\n',A1)

The augmented matrix [A|b] is:
 [[ 2.  1.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  1.  2.  3.]]


### 2.1. Elimination: Transform of A to U 

Use the first row of A1 to eliminate the 'rest' of the first column of A1

In [8]:
A1[1,:]=A1[1,:]-(A1[1,0]/A1[0,0])*A1[0,:]
A1[2,:]=A1[2,:]-(A1[2,0]/A1[0,0])*A1[0,:]
print('After subtracting row-1 from row-2 and row-3:\n',A1)

After subtracting row-1 from row-2 and row-3:
 [[ 2.   1.   1.   1. ]
 [ 0.   1.5  0.5  1.5]
 [ 0.   0.5  1.5  2.5]]


Use the second row of A1 to eliminate the 'rest' of the second column of A1

In [9]:
A1[2,:]=A1[2,:]-(A1[2,1]/A1[1,1])*A1[1,:]
print('After subtracting row-2 from row-3:\n',A1)

After subtracting row-2 from row-3:
 [[ 2.          1.          1.          1.        ]
 [ 0.          1.5         0.5         1.5       ]
 [ 0.          0.          1.33333333  2.        ]]


### 2.2. Backward substitution (bottom to top) 

In [10]:
U=np.zeros([3,3])
U[0:3,0:3]=A1[0:3,0:3].copy()
print('The U-form of matrix A is:\n',U)

The U-form of matrix A is:
 [[ 2.          1.          1.        ]
 [ 0.          1.5         0.5       ]
 [ 0.          0.          1.33333333]]


In [11]:
b=np.zeros([3])
b[0:3]=A1[0:3,3].copy()
print('The modified coefficient vector is:\n',b)

The modified coefficient vector is:
 [ 1.   1.5  2. ]


Now we have to solve the following equations.
$$
  2x+y+z=1 \\
    1.5y+0.5z = 1.5 \\
    1.33333333z=2
$$

Let's start by solving the last equation.
$$
1.33333333z=2 \Rightarrow z = 2/1.33333333
$$

In [12]:
x=np.zeros([3])
x[2]=b[2]/U[2,2]
print(x)

[ 0.   0.   1.5]


Now let's  solve the second equation
$$
1.5y+0.5z = 1.5
$$
by substituting the value of z=1.5
$$
1.5y+0.5(1.5)=1.5\\
\rightarrow 1.5y+0.75 = 1.5 \\
\rightarrow 1.5y=0.75\\
\rightarrow y = 0.75/1.5 = 0.5
$$

In [13]:
x[1]=(b[1]-U[1,2]*x[2])/U[1,1]
print(x)

[ 0.   0.5  1.5]


Now, the first equation
$$
  2x+y+z=1 \\
\rightarrow 2x+0.5+1.5=1\\
\rightarrow 2x=-1\\
\rightarrow x=-1/2
$$

In [14]:
x[0]=(b[0]-U[0,2]*x[1]-U[0,2]*x[2])/U[0,0]
print(x)

[-0.5  0.5  1.5]


### 2.3. Generalizing elimination followed by substitution 

![board%20work%20-6.jpg](boardwork/board%20work%20-6.jpg)
![board%20work%20-8.jpg](boardwork/board%20work%20-8.jpg)

In [34]:
import numpy as np

A=np.array([[2,1,1],[1,2,1],[1,1,2]],float) #NOTE: float
b=np.array([1,2,3],float)
x=np.zeros(3,float)

N=A.shape[0]

print(A)

print('\nTransformation: A -> U\n')

for k in range(0,N-1):
    for i in range(k+1,N):
        lam=A[k,i]/A[k,k]
        A[i,:]=A[i,:]-lam*A[k,:]
        b[i]=b[i]-lam*b[k]

print(A)

print(b)

print('\nBackward substitution to get x\n')

x[2]=b[2]/A[2,2]
for k in range(N-2,-1,-1):
    x[k]=b[k]
    for j in range(k+1,N):
        x[k]=x[k]-A[k,j]*x[j]
    x[k]=x[k]/A[k,k]

print(x)

[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]

Transformation: A -> U

[[ 2.          1.          1.        ]
 [ 0.          1.5         0.5       ]
 [ 0.          0.          1.33333333]]
[ 1.   1.5  2. ]

Backward substitution to get x

[-0.5  0.5  1.5]
