# Content:
1. [Data modeling](#1.-Data-modeling)
2. [Matrix inverse](#2.-Matrix-inverse)
3. [Vandermonde matrix](#3.-Vandermonde-matrix)
4. [Polynomial fitting](#4.-Polynomial-fitting)

## 1. Data modeling

![board%20work%20-19.jpg](boardwork/board%20work%20-19.jpg)
![board%20work%20-20.jpg](boardwork/board%20work%20-20.jpg)
![board%20work%20-21.jpg](boardwork/board%20work%20-21.jpg)
![board%20work%20-22.jpg](boardwork/board%20work%20-22.jpg)
![board%20work%20-23.jpg](boardwork/board%20work%20-23.jpg)
![board%20work%20-24.jpg](boardwork/board%20work%20-24.jpg)

## 2. Matrix inverse

Let's use Numpy's implementation to determine the matrix inverse. You can check if the inverse has come out as expected by multiplying with the given matrix. 

In [1]:
import numpy as np 

A = np.array([[1,2],[3,4]]) 
Ainv = np.linalg.inv(A)

print(A,'\n') 
print(Ainv,'\n')
I=np.dot(A,Ainv)
print(I)

[[1 2]
 [3 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


## 3. Vandermonde matrix

Numpy has a function to calculate the Vandermonde matrix. 

In [44]:
import numpy as np 

x = np.array([1, 2, 3, 5])

# To fit a straight-line, polynomial of degree 1
D=3

np.vander(x, D+1, increasing=True) #NOTE: argument is D+1

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [45]:
D=3
np.vander(x, D+1) #Note the order

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [4]:
D=4
np.vander(x, D+1, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   5,  25, 125, 625]])

## 4. Polynomial fitting

In [55]:
def polyfit(x,y,D):
    '''
        Fits a given set of data x,y to a polynomial of degree D
    '''
    import numpy as np 
    
    #N=x.shape()
    
    X=np.vander(x, D+1, increasing=True)
    XT=np.transpose(X)
    
    A=np.matmul(XT,X)
    Ainv=np.linalg.inv(A)
    
    b=np.matmul(XT,y)
    
    a=np.matmul(Ainv,b)
    
    return(a)

#=== Let's fit a data from a parabola to a polynomial of degree 'D'

x_i=-2.0
x_f=2.0
dx=0.5
x=np.arange(x_i, x_f+dx, dx, float) # start, stop, step, dtype

print(x)

y=-0.4*x**2

D=3  # Degree = 3
a=polyfit(x,y,D)

for i in range(D+1):
    print(i,a[i])

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
0 4.4408920985e-16
1 -2.03104773304e-16
2 -0.4
3 5.88131613494e-17


Only the quadratic term survives, all other coefficients are zero!

To evaluate the polynomial, i.e., the estimated values of y, one can write another function, called polyval.

In [40]:
def polyval(a,x):
    '''
        Determines the value of the polynomial using x and the coefficient vector a
    '''
    import numpy as np
    D=a.shape[0]
    N=x.shape

    y=np.zeros(N)
    for i in range(D):
        y=y+a[i]*x**i
    
    return(y)

yfit=polyval(a,x)
print(yfit)

[ -1.60000000e+00  -9.00000000e-01  -4.00000000e-01  -1.00000000e-01
   4.44089210e-16  -1.00000000e-01  -4.00000000e-01  -9.00000000e-01
  -1.60000000e+00]
