# Content:
1. [Numpy eigen](#numpy)
2. [Power method](#power)
3. [3x3 example](#3x3)

## 1. <a name="eigen">Numpy eigen</a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[2,4]])
print(A)

[[1 2]
 [2 4]]


In [3]:
E,V=np.linalg.eig(A)
print('Eigenvalues')
print(E)
print('\n')
print('Eigenvectors')
print(V)

Eigenvalues
[0. 5.]


Eigenvectors
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


## 2. <a name="power">Power method</a>

In [4]:
import numpy as np

def power_method(A,max_iter):
    
    #No. of rows
    N=A.shape[1] 
    
    x=np.random.rand(N)
    print(x)
    
    for i_iter in range(max_iter):
        
        x=np.dot(A,x)
        
        x_norm=np.linalg.norm(x)
        
        x=x/x_norm
        print(x)
    
    return(x)

In [5]:
x=power_method(A,10)

[0.52777337 0.70860405]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]


In [6]:
#largest eigenvalue
E=np.dot(x,np.dot(A,x))
print(E)

5.000000000000001


## 3. <a name="3x3">3x3 example</a>

In [7]:
A=np.array([[1,2,3],[2,4,5],[3,5,6]])
print(A)

[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [8]:
E,V=np.linalg.eig(A)
print('Eigenvalues')
print(E)
print('\n')
print('Eigenvectors')
print(V)

Eigenvalues
[11.34481428 -0.51572947  0.17091519]


Eigenvectors
[[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]


In [9]:
x=power_method(A,10)

[0.06787062 0.45206492 0.6573161 ]
[0.33530659 0.59574693 0.72983223]
[0.3275975  0.59085913 0.73726885]
[0.32800209 0.59101687 0.73696247]
[0.3279845  0.59100871 0.73697685]
[0.32798531 0.59100906 0.7369762 ]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]


In [10]:
#largest eigenvalue
E=np.dot(x,np.dot(A,x))
print(E)

11.344814282762082
