# Content:
1. [Systems of linear algebraic equations](#1.-Systems-of-linear-algebraic-equations)

In [1]:
import numpy as np

A=np.array([[2,1,1],[1,2,1],[1,1,2]])
b=np.array([1,2,3])

#=== Augmented matrix
A1=np.zeros([3,4])
A1[0:3,0:3]=A.copy()
A1[0:3,3]=b.copy()

print('The augmented matrix [A|b] is:\n',A1)

The augmented matrix [A|b] is:
 [[ 2.  1.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  1.  2.  3.]]


### Elimination: Transform A to U 

Use first row of A1 to eliminate the 'rest' of the first column of A1

In [2]:
A1[1,:]=A1[1,:]-(A1[1,0]/A1[0,0])*A1[0,:]
print('After subtracting row-1 from row-2:\n',A1)

After subtracting row-1 from row-2:
 [[ 2.   1.   1.   1. ]
 [ 0.   1.5  0.5  1.5]
 [ 1.   1.   2.   3. ]]


In [3]:
A1[2,:]=A1[2,:]-(A1[2,0]/A1[0,0])*A1[0,:]
print('After subtracting row-1 from row-3:\n',A1)

After subtracting row-1 from row-3:
 [[ 2.   1.   1.   1. ]
 [ 0.   1.5  0.5  1.5]
 [ 0.   0.5  1.5  2.5]]


In [4]:
A1[2,:]=A1[2,:]-(A1[2,1]/A1[1,1])*A1[1,:]
print('After subtracting row-2 from row-3:\n',A1)

After subtracting row-2 from row-3:
 [[ 2.          1.          1.          1.        ]
 [ 0.          1.5         0.5         1.5       ]
 [ 0.          0.          1.33333333  2.        ]]


### Backward substitution (bottom to top) 

In [5]:
U=np.zeros([3,3])
U[0:3,0:3]=A1[0:3,0:3].copy()
print('The U-form of matrix A is:\n',U)

The U-form of matrix A is:
 [[ 2.          1.          1.        ]
 [ 0.          1.5         0.5       ]
 [ 0.          0.          1.33333333]]


In [6]:
b=np.zeros([3])
b[0:3]=A1[0:3,3].copy()
print('The modified coefficient vector is:\n',b)

The modified coefficient vector is:
 [ 1.   1.5  2. ]


Now we have to solve the following equations.
$$
  2x+y+z=1 \\
    1.5y+0.5z = 1.5 \\
    1.33333333z=2
$$

Let's start by solving the last equation.
$$
1.33333333z=2 \Rightarrow z = 2/1.33333333
$$

In [7]:
x=np.zeros([3])
x[2]=b[2]/U[2,2]
print(x)

[ 0.   0.   1.5]


Now let's  solve the second equation
$$
1.5y+0.5z = 1.5
$$
by substituting the value of z=1.5
$$
1.5y+0.5(1.5)=1.5\\
\rightarrow 1.5y+0.75 = 1.5 \\
\rightarrow 1.5y=0.75\\
\rightarrow y = 0.75/1.5 = 0.5
$$

In [8]:
x[1]=(b[1]-U[1,2]*x[2])/U[1,1]
print(x)

[ 0.   0.5  1.5]


Now, the first equation
$$
  2x+y+z=1 \\
\rightarrow 2x+0.5+1.5=1\\
\rightarrow 2x=-1\\
\rightarrow x=-1/2
$$

In [9]:
x[0]=(b[0]-U[0,2]*x[1]-U[0,2]*x[2])/U[0,0]
print(x)

[-0.5  0.5  1.5]
