# Content:
1. [Numpy eigen](#numpy)
2. [Power method](#power)
3. [3x3 example](#3x3)
4. [Jacobi method](#jacobi)

## 1. <a name="eigen">Numpy eigen</a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[2,4]])
print(A)

[[1 2]
 [2 4]]


In [3]:
E,V=np.linalg.eig(A)
print('Eigenvalues')
print(E)
print('\n')
print('Eigenvectors')
print(V)

Eigenvalues
[0. 5.]


Eigenvectors
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


## 2. <a name="power">Power method</a>

In [4]:
import numpy as np

def power_method(A,max_iter):
    
    #No. of rows
    N=A.shape[1] 
    
    x=np.random.rand(N)
    print(x)
    
    for i_iter in range(max_iter):
        
        x=np.dot(A,x)
        
        x_norm=np.linalg.norm(x)
        
        x=x/x_norm
        print(x)
    
    return(x)

In [5]:
x=power_method(A,10)

[0.2470949  0.26614184]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]
[0.4472136  0.89442719]


In [6]:
#largest eigenvalue
E=np.dot(x,np.dot(A,x))
print(E)

5.000000000000001


## 3. <a name="jacobi">Jacobi method</a>

In [7]:
A=np.array([[1,2],[2,4]])
print(A)

[[1 2]
 [2 4]]


In [8]:
th=(1.0/2.0)*np.arctan((2*A[0,1])/(A[0,0]-A[1,1]))

In [9]:
V=np.array([[np.cos(th),np.sin(th)],[np.sin(th),-np.cos(th)]])

In [10]:
Vt=np.transpose(V)
E=np.matmul(Vt,np.matmul(A,V))
print(E)

[[0.00000000e+00 4.53932125e-17]
 [0.00000000e+00 5.00000000e+00]]


In [11]:
print(V)

[[ 0.89442719 -0.4472136 ]
 [-0.4472136  -0.89442719]]


## 4. <a name="3x3">3x3 example</a>

In [12]:
A=np.array([[1,2,3],[2,4,5],[3,5,6]])
print(A)
E,V=np.linalg.eig(A)
print('Eigenvalues')
print(E)
print('\n')
print('Eigenvectors')
print(V)

[[1 2 3]
 [2 4 5]
 [3 5 6]]
Eigenvalues
[11.34481428 -0.51572947  0.17091519]


Eigenvectors
[[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]


#### Power method

In [13]:
x=power_method(A,10)

[0.88615945 0.31907561 0.86713356]
[0.32517423 0.58200401 0.7453409 ]
[0.32838798 0.59107192 0.73674644]
[0.32797113 0.591001   0.73698898]
[0.32798598 0.59100934 0.73697568]
[0.32798525 0.59100903 0.73697625]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]
[0.32798528 0.59100905 0.73697623]


In [14]:
E=np.dot(x,np.dot(A,x))
print(E)

11.34481428276208


#### Jacobi method

In [15]:
print(A)

[[1 2 3]
 [2 4 5]
 [3 5 6]]


##### Iteration-1

In [16]:
i=1
j=2
th=(1.0/2.0)*np.arctan((2*A[i,j])/(A[i,i]-A[j,j]))

In [17]:
V=np.identity(3)
V[i,i]=+np.cos(th)
V[i,j]=+np.sin(th)
V[j,i]=+np.sin(th)
V[j,j]=-np.cos(th)
print(V)

[[ 1.          0.          0.        ]
 [ 0.          0.77334214 -0.63398891]
 [ 0.         -0.63398891 -0.77334214]]


In [18]:
Vt=np.transpose(V)
Anew=np.matmul(Vt,np.matmul(A,V))
print(Anew)

[[ 1.00000000e+00 -3.55282434e-01 -3.58800424e+00]
 [-3.55282434e-01 -9.90195136e-02  2.15144758e-16]
 [-3.58800424e+00  6.20717275e-16  1.00990195e+01]]


##### Iteration-2

In [19]:
i=0
j=2
th=(1.0/2.0)*np.arctan((2*A[i,j])/(A[i,i]-A[j,j]))
#======
V=np.identity(3)
V[i,i]=+np.cos(th)
V[i,j]=+np.sin(th)
V[j,i]=+np.sin(th)
V[j,j]=-np.cos(th)
print(V,'\n')
#=====
Vt=np.transpose(V)
Anew=np.matmul(Vt,np.matmul(Anew,V))
print(Anew)

[[ 0.90558942  0.         -0.4241554 ]
 [ 0.          1.          0.        ]
 [-0.4241554   0.         -0.90558942]] 

[[ 5.39336579 -0.32174001  5.79201454]
 [-0.32174001 -0.09901951  0.15069496]
 [ 5.79201454  0.15069496  5.70565372]]
